### ISSUE TITLE
Review accessability

### ISSUE THREAD

**Issue by FatimaZelay** [Saif8599/all-human-accessible-website#8]
Probeer bij de zoek-button een naam te geven, eventueel met aria-label. Probeer de a.logo en a.footer-logo toegankelijk te maken voor screen-readers door ook een aria-label te geven. Voor de rest ziet het er goed uit.

**Comment by Saif8599** [comment]
https://github.com/Saif8599/all-human-accessible-website/commit/14aebaa5d4e2e1ecccea9dbf84988768e9da482d
